version: '3.1'

services:

  ubuntu:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
    volumes:
      - .:/var/www/html/test

  node-debian:
    build:
      context: .
      dockerfile: node-debian.Dockerfile
    volumes:
      - .:/var/www/html/test
