version: '3.1'

services:

  ubuntu:
    working_dir: /var/app
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
    volumes:
      - .:/var/app

  node-debian:
    working_dir: /var/app
    build:
      context: .
      dockerfile: node-debian.Dockerfile
    volumes:
      - .:/var/app
