version: '3.1'

services:

  ubuntu:
    working_dir: /root/scripts
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
    deploy:
      mode: replicated
      replicas: 0
    volumes:
      - ./scripts:/root/scripts
      - ./app:/var/www/html/app

  node-debian:
    working_dir: /root/scripts
    build:
      context: .
      dockerfile: node-debian.Dockerfile
    deploy:
      mode: replicated
      replicas: 0
    volumes:
      - ./scripts:/root/scripts
      - ./app:/var/www/html/app

volumes:
  maintenancedata:
