version: '3.1'

services:

  ubuntu:
    working_dir: /app
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
    volumes:
      - .:/app

  debian:
    working_dir: /app
    build:
      context: .
      dockerfile: debian.Dockerfile
    volumes:
      - .:/app
