version: '3.1'

services:

  ubuntu:
    working_dir: /app
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
    volumes:
      - .:/app

  node-debian:
    working_dir: /app
    build:
      context: .
      dockerfile: node-debian.Dockerfile
    volumes:
      - .:/app
