version: '3.1'

services:

  ubuntu:
    working_dir: /var/www/html/app
    build:
      context: .
      dockerfile: ubuntu.Dockerfile

  node-debian:
    working_dir: /var/www/html/app
    build:
      context: .
      dockerfile: node-debian.Dockerfile
